### ISSUE TITLE
Random generated images are not getting saved

### ISSUE THREAD

**Issue by pankaj-pundir** [bloomberg/scatteract#3]
I set up the environment accordingly but while running the code the images are not being saved in the data/plots_v1 folder and other files also have 0 Byte size.
Decreased the generated size for testing.
`python generate_random_scatter.py --directory plots_v1 --n_train 250 --n_test 5
`

**Comment by pankaj-pundir** [comment]
*After Reading the code*
 i figured out
its actually getting error on 
[generate_random_scatter](https://github.com/bloomberg/scatteract/blob/085df9e37efc90575d25cc2bbfe733f4c0ecc019/generate_random_scatter.py#L45)
fixed it after editing
`font_list = matplotlib.font_manager.get_fontconfig_fonts() `
`font_list = [i for i in font_list] `

**Comment by ramdhan1989** [comment]
Hi @pankaj-pundir for me it returns the empty list
```
font_list = matplotlib.font_manager.get_fontconfig_fonts()
font_list = [i for i in font_list] 
font_list
```
